github:
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: gitbox@yetus.apache.org
  issues: gitbox@yetus.apache.org
  pullrequests: gitbox@yetus.apache.org
  jira_options: link label worklog
